### ISSUE TITLE
Compatibility with kubelet v1.20

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/linstor-csi#113]
Hi, it seems we need to update linstor-csi manifests for v1.20 somehow
The driver is not working with kubelet v1.20, in case to mount volume the following message occurs:

```
  Warning  FailedMount  26s   kubelet, m5c27     MountVolume.NewMounter initialization failed for volume "pvc-7819a76f-f388-4b63-8f6e-d10517c27e36" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string
```

Setting `fsGroupPolicy: None` for CSIDriver resource as suggested @andyzhangx in https://github.com/kubernetes-csi/csi-driver-smb/issues/176#issuecomment-748477711 does not making any effect.
Possible workaround is to run kubelet with `--feature-gates=CSIVolumeFSGroupPolicy=false` for now.

- Similar issue for csi-driver-smb: https://github.com/kubernetes-csi/csi-driver-smb/issues/176
- More about the feature: https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/

**Comment by WanzenBug** [comment]
I'm running on a fresh v1.20.4 installation, and I do not experience this issue. My CSIDriver object ends up looking like this:
```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    linstor.linbit.com/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1beta1","kind":"CSIDriver","metadata":{"creationTimestamp":null,"name":"linstor.csi.linbit.com"},"spec":{"attachRequired":true,"podInfoOnMount":true}}
  creationTimestamp: "2021-03-17T09:36:30Z"
  managedFields:
  - apiVersion: storage.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:linstor.linbit.com/last-applied-configuration: {}
      f:spec:
        f:attachRequired: {}
        f:fsGroupPolicy: {}
        f:podInfoOnMount: {}
        f:volumeLifecycleModes: {}
    manager: linstor.linbit.com/pkg/k8s/reconcileutil
    operation: Update
    time: "2021-03-17T09:36:30Z"
  name: linstor.csi.linbit.com
  resourceVersion: "50007263"
  uid: 47c57210-1b5f-4213-baab-4eaa9f8e6803
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
```

so it seems the `fsGroupPolicy` is automatically added by kubernetes (note that I am using the operator, which still uses `storage.k8s.io/v1beta1`, which gets converted to `storage.k8s.io/v1` on the API server)

**Comment by andyzhangx** [comment]
I doubt it's related to OS, Ubuntu 18.04 works while 20.04 does not work.

**Comment by kvaps** [comment]
Hmm, sorry, it's possible that I was wrong.

Currently in this cluster I'm having kubelet v1.20 and apiservers v1.19 which can cause this behavior. I'm going to update it in a while.
But it would be nice if someone could confirm this issue.

**Comment by kvaps** [comment]
It seems the problem was caused by incompatibility of the versions kubelet v1.20 and apiservers v1.19.

Right now all apiservers already upgraded and I don't see the such problem.
Closing issue for now.
