### ISSUE TITLE
Questions about setting qos

### ISSUE THREAD

**Issue by lts9527** [piraeusdatastore/linstor-csi#191]
can I set qos in one of pvc, pv, SC

**Comment by lts9527** [comment]
I want to limit disk io
Like here: https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#_qos_settings
I don't have parameters available in the storage class to see information about limiting disk io Can this be achieved

**Comment by WanzenBug** [comment]
You can set these properties like this:
```yaml
parameters:
  property.linstor.csi.linbit.com/sys/fs/blkio_throttle_read: "3000"
```

**Comment by lts9527** [comment]
I'm sincerely appreciative
