### ISSUE TITLE
Recommended upgrade path for linstor-csi

### ISSUE THREAD

**Issue by Retrospector** [piraeusdatastore/linstor-csi#59]
I didn't find something about it in the documentation, so I guess I'll ask here.

Is there a recommended way of updating the CSI? 
We've deployed the CSI a while back with the 1.14 version of the deployment file. Now the cluster got upgraded over time to now k8s 1.17 while the linstor CSI remained unchanged. Is it possible to remove the CSI and deploy the newest release without the existing volumes getting "lost" or "orphaned"?

Sorry if this is a stupid question, I'm still new to the Kubernetes world.
I appreciate your insights!

**Comment by kvaps** [comment]
Hi, I'm not a LINBIT member so my answer can't be considered as authorized.

But we're always removing csi-driver with all related CRD's and installing the new version without any problems and downtime for already running resources.

**Comment by Retrospector** [comment]
Hi @kvaps, thank you for your reply!

I'll give it a try on monday. Probably only the regular linstor-csi for now, but thanks for letting me know about your Helm project, it looks very promising.

Have a great weekend!

**Comment by Retrospector** [comment]
Sorry for leaving this open for so long, I did remove the old definitions and applied the new ones and it worked fine.
