### ISSUE TITLE
Missing documentation of many available StorageClass parameters

### ISSUE THREAD

**Issue by immanuelfodor** [piraeusdatastore/linstor-csi#98]
Hi Everyone,

In the example of https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/deploy/all.yaml I've seen `StorageClass` parameters that are not documented neither at https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-advanced-configuration nor in this repo (also not in piraeus and piraeus-operator as I checked). 

For example, the meaning of `allowRemoteVolumeAccess` or `placementPolicy` can only be found with a repo search in some Go source code and the changelog file:
- https://github.com/piraeusdatastore/linstor-csi/blob/master/CHANGELOG.md#070---2019-08-07
- https://github.com/piraeusdatastore/linstor-csi/blob/master/pkg/volume/volume.go#L73
- https://github.com/piraeusdatastore/linstor-csi/blob/master/pkg/topology/topology.go#L29

I managed to get the information what I was searching for from the comments but since the user should create the SC on their own (https://github.com/piraeusdatastore/piraeus-operator/issues/125#issuecomment-735814728), and the operator repo doesn't mention that, there could be a place for improvement related to SC examples and documentation of the available options. A documentation page here with some examples of common combinations and a link back here from the operator readme's install guide could work nicely together.

Great project by the way, this is just an idea for enhancement :)

**Comment by WanzenBug** [comment]
The User Guide on linbit.com now has a section with all currently supported parameters: https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-sc-parameters

**Comment by immanuelfodor** [comment]
Wow, it's been extended indeed, looks great. Do you plan to give a link back to there from the readme with an example SC maybe?

**Comment by WanzenBug** [comment]
Done in #109
